export const en = {
  nav: {
    services: 'Services',
    projects: 'Projects',
    about: 'About',
    howWeWork: 'How we work',
    contact: 'Contact',
  },
  hero: {
    badge: 'Loved by our clients',
    headline: 'Tech brains on tap.',
    headlineAccent: 'You focus on business. We handle the tech.',
    tagline: 'Software house for startups and companies. From concept to launch, with clarity and delivery.',
    ctaConsult: 'Book a free consultation',
    ctaProjects: 'See success cases',
  },
  heroAi: 'We present options. You decide. We build.',
  coreLabel: 'Our core',
  coreDeliverablesLabel: 'Deliverables',
  coreTimeline: [
    { step: 1, title: 'Discovery', deliverable: 'Alignment brief', description: 'We align on the problem, goals, and constraints. You get a clear brief so we can propose options.' },
    { step: 2, title: 'Options', deliverable: 'Proposal with 2–3 options', description: 'We present options (tech, scope, timeline). You compare and choose with clarity.' },
    { step: 3, title: 'Decision', deliverable: 'Signed scope & kickoff', description: 'You decide. We lock scope, timeline, and kick off. No surprises from here.' },
    { step: 4, title: 'Build', deliverable: 'Working product in sprints', description: 'We build in iterations. You see progress early; we adjust as we go.' },
    { step: 5, title: 'Launch', deliverable: 'Live product & handover', description: 'We deliver, hand over, and support go-live. You get docs and peace of mind.' },
  ],
  stats: {
    projects: 'Projects delivered',
    satisfaction: 'Satisfaction',
    sinceMarket: 'In the market since',
    yearsInMarket: 'Years in the market',
    onTime: 'On-time delivery',
  },
  services: {
    title: 'Our Services',
    subtitle: 'From discovery to launch, we cover the full product cycle with quality and speed.',
    web: {
      title: 'Web Apps',
      description: 'Next.js, React, Node. Fast, accessible, SEO-friendly experiences.',
    },
    mobile: {
      title: 'Mobile',
      description: 'Flutter for iOS and Android. Modern UX, native performance, store-ready.',
    },
    apis: {
      title: 'APIs & Data',
      description: 'Scalable APIs, integrations, relational databases, and data pipelines.',
    },
    cta: 'View all services',
  },
  howWeWork: {
    title: 'How we work',
    subtitle: 'We give you options to decide on the business. Once you choose, we build.',
    steps: [
      { title: 'Discovery', description: 'We align on the problem and your goals. We present options — tech, scope, timeline — so you can decide with clarity.' },
      { title: 'You decide', description: 'You choose the direction that fits your business. No pressure. We\'re here to advise; the call is yours.' },
      { title: 'We build', description: 'With the decision made, we build. You see progress in iterations; we adjust as we go.' },
    ],
    aiLine: 'Clear options first. Your decision. Then we build.',
    cta: 'See our process',
  },
  projects: {
    title: 'Projects',
    subtitle: 'Selected client work. Real problems, real solutions.',
    cta: 'View all projects',
    empty: 'More projects coming soon.',
  },
  whyUs: {
    title: 'Why work with us',
    items: [
      { title: 'Clear process', description: 'Discovery, scope, and timeline from day one. No surprises.' },
      { title: 'Modern stack', description: 'Next.js, Flutter, type-safe code. Your product stays maintainable.' },
      { title: 'AI-accelerated', description: 'We use AI to deliver faster and keep quality high.' },
    ],
  },
  contact: {
    title: 'Get in touch',
    subtitle: 'Have an idea? Let\'s turn it into reality.',
    name: 'Name',
    email: 'Email',
    message: 'Message',
    send: 'Send message',
    sending: 'Sending...',
    success: 'Message sent! We\'ll reply soon.',
  },
  about: {
    title: 'About Devlup',
    subtitle: 'Our story, mission, and values',
    story: {
      title: 'Our story',
      p1: 'We started as freelance developers in 2019, working on independent projects and helping startups turn ideas into reality. Over time, we saw that the market needed more than code: a strategic partner who understands both technology and business.',
      p2: 'Today, Devlup is a software house recognized in Canada, specialized in scalable digital products. We\'ve delivered 50+ projects, from MVPs for startups to complex platforms for established companies.',
      p3: 'Our mission remains the same: build not just products, but lasting partnerships with our clients. We believe project success goes beyond code — it\'s in clear communication, deep understanding of the business, and commitment to measurable results.',
    },
  },
  footer: {
    company: 'Devlup',
    tagline: 'Software house in Canada • devlup.ca',
    companyLabel: 'Company',
    legal: 'Legal',
    terms: 'Terms',
    privacy: 'Privacy',
    rights: 'All rights reserved.',
  },
  meta: {
    title: 'Devlup — Software House',
    description: 'Software house specialized in scalable digital products for startups and companies. From concept to launch.',
  },
} as const;
