export const pt = {
  nav: {
    services: 'Serviços',
    projects: 'Projetos',
    about: 'Sobre',
    howWeWork: 'Como trabalhamos',
    contact: 'Contato',
  },
  hero: {
    badge: 'Nossos clientes adoram trabalhar conosco',
    headline: 'Tech brains on tap.',
    headlineAccent: 'Você foca no negócio. Nós cuidamos da tech.',
    tagline: 'Software house para startups e empresas. Do conceito ao lançamento, com clareza e entrega.',
    ctaConsult: 'Agende uma consulta gratuita',
    ctaProjects: 'Ver cases de sucesso',
  },
  heroAi: 'Apresentamos opções. Você decide. Nós construímos.',
  coreLabel: 'Nosso core',
  coreDeliverablesLabel: 'Entregáveis',
  coreTimeline: [
    { step: 1, title: 'Discovery', deliverable: 'Brief de alinhamento', description: 'Alinhamos problema, objetivos e restrições. Você recebe um brief claro para propormos opções.' },
    { step: 2, title: 'Options', deliverable: 'Proposta com 2–3 opções', description: 'Apresentamos opções (tech, escopo, prazo). Você compara e escolhe com clareza.' },
    { step: 3, title: 'Decision', deliverable: 'Escopo assinado & kickoff', description: 'Você decide. Travamos escopo, prazo e damos o kickoff. Sem surpresas daqui pra frente.' },
    { step: 4, title: 'Build', deliverable: 'Produto funcionando em sprints', description: 'Construímos em iterações. Você vê progresso cedo; ajustamos no caminho.' },
    { step: 5, title: 'Launch', deliverable: 'Produto no ar & handover', description: 'Entregamos, fazemos handover e damos suporte ao go-live. Você recebe docs e tranquilidade.' },
  ],
  stats: {
    projects: 'Projetos entregues',
    satisfaction: 'Satisfação',
    sinceMarket: 'No mercado desde',
    yearsInMarket: 'Anos no mercado',
    onTime: 'Entrega no prazo',
  },
  services: {
    title: 'Nossos Serviços',
    subtitle: 'Do discovery ao lançamento, cobrimos todo o ciclo de produto com qualidade e velocidade.',
    web: {
      title: 'Web Apps',
      description: 'Next.js, React, Node. Experiências rápidas, acessíveis e SEO-friendly.',
    },
    mobile: {
      title: 'Mobile',
      description: 'Flutter iOS/Android. UX moderna, performance nativa, publicação nas stores.',
    },
    apis: {
      title: 'APIs & Dados',
      description: 'APIs escaláveis, integrações, bancos relacionais e pipelines de dados.',
    },
    cta: 'Ver todos os serviços',
  },
  howWeWork: {
    title: 'Como trabalhamos',
    subtitle: 'Damos opções para você decidir no negócio. Depois que você escolhe, nós construímos.',
    steps: [
      { title: 'Discovery', description: 'Alinhamos problema e objetivos. Apresentamos opções — tech, escopo, prazo — para você decidir com clareza.' },
      { title: 'Você decide', description: 'Você escolhe o rumo que faz sentido para o negócio. Sem pressão. Nós orientamos; a decisão é sua.' },
      { title: 'Nós construímos', description: 'Com a decisão tomada, nós construímos. Você acompanha em iterações; ajustamos no caminho.' },
    ],
    aiLine: 'Opções primeiro. Sua decisão. Depois nós construímos.',
    cta: 'Ver nosso processo',
  },
  projects: {
    title: 'Projetos',
    subtitle: 'Trabalhos selecionados. Problemas reais, soluções reais.',
    cta: 'Ver todos os projetos',
    empty: 'Mais projetos em breve.',
  },
  whyUs: {
    title: 'Por que trabalhar conosco',
    items: [
      { title: 'Processo claro', description: 'Discovery, escopo e prazo desde o primeiro dia. Sem surpresas.' },
      { title: 'Stack moderna', description: 'Next.js, Flutter, código type-safe. Seu produto permanece sustentável.' },
      { title: 'Acelerado por IA', description: 'Usamos IA para entregar mais rápido e manter a qualidade alta.' },
    ],
  },
  contact: {
    title: 'Fale conosco',
    subtitle: 'Tem uma ideia? Vamos transformá-la em realidade.',
    name: 'Nome',
    email: 'E-mail',
    message: 'Mensagem',
    send: 'Enviar mensagem',
    sending: 'Enviando...',
    success: 'Mensagem enviada! Responderemos em breve.',
  },
  about: {
    title: 'Sobre a Devlup',
    subtitle: 'Nossa história, missão e valores',
    story: {
      title: 'Nossa história',
      p1: 'Começamos como desenvolvedores freelancers em 2019, trabalhando em projetos independentes e ajudando startups a transformar suas ideias em realidade. Com o tempo, percebemos que o mercado precisava de mais do que apenas código: precisava de um parceiro estratégico que entendesse tanto de tecnologia quanto de negócios.',
      p2: 'Hoje, a Devlup é uma software house reconhecida no Canadá, especializada em produtos digitais escaláveis. Já entregamos mais de 50 projetos, desde MVPs para startups até plataformas complexas para empresas estabelecidas.',
      p3: 'Nossa missão continua a mesma: construir não apenas produtos, mas parcerias duradouras com nossos clientes. Acreditamos que o sucesso de um projeto vai além do código — está na comunicação clara, no entendimento profundo do negócio e no compromisso com resultados mensuráveis.',
    },
  },
  footer: {
    company: 'Devlup',
    tagline: 'Software house no Canadá • devlup.ca',
    companyLabel: 'Empresa',
    legal: 'Legal',
    terms: 'Termos',
    privacy: 'Privacidade',
    rights: 'Todos os direitos reservados.',
  },
  meta: {
    title: 'Devlup — Software House',
    description: 'Software house especializada em produtos digitais escaláveis para startups e empresas. Do conceito ao lançamento.',
  },
} as const;
